excludes = [
    "*.lock",
    "*.patch",
    "package-lock.json",
    "go.mod",
    "go.sum",
    ".gitattributes",
    ".gitignore",
    ".gitmodules",
    ".hgignore",
    ".svnignore",
    "LICENSE",
    "zz-mosh/m4/**",
    "**/*.pb.cc",
    "**/*.pb.h",
    "zz-mosh/scripts/mosh.pl",
    "result",
    "result-*",
    ".direnv/**",
    ".tmp/**",
    "*.lock",
    "*.md",
    "flake.lock",
    "conformist.toml",
]

[formatter.clang-format]
command = "/nix/store/bw3x1vkn4gdbhmjzqnjrznx7zd6ylc2k-clang-tools-21.1.8/bin/clang-format"
config-files = [".clang-format"]
excludes = []
includes = [
    "*.c",
    "*.cc",
    "*.cpp",
    "*.h",
    "*.hh",
    "*.hpp",
    "*.glsl",
    "*.vert",
    ".tesc",
    ".tese",
    ".geom",
    ".frag",
    ".comp",
]
options = ["-i"]

[formatter.nixfmt]
command = "/nix/store/cn0f42d8p48g718nh2zsgl96zjx207hi-nixfmt-1.2.0/bin/nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.shfmt]
command = "/nix/store/cbdgj2ml8hvs4pzrms38n2s76hbksrp4-shfmt-3.13.1/bin/shfmt"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-w", "-i", "2", "-s"]

[linter.eng-versioning]
command = "/nix/store/7l3h1x7183r44r2129i5w9aap303fqn5-conformist-eng-versioning/bin/conformist-eng-versioning"
excludes = []
includes = ["version.env"]
options = []
passes-files = false

[linter.eng-versioning-deprecated-file]
command = "/nix/store/njy8k85mlf41zhwh6b40hnsg2bsg2bs4-conformist-eng-versioning-deprecated-file/bin/conformist-eng-versioning-deprecated-file"
excludes = []
includes = ["flake.nix", "version.txt"]
options = []
passes-files = false

[linter.flake-lock]
command = "/nix/store/l5s7cf6jkkn22wid4qynxrxd2bpc8h95-conformist-flake-lock/bin/conformist-flake-lock"
excludes = []
includes = ["flake.nix"]
options = []
passes-files = false

[linter.flake-outputs]
command = "/nix/store/cn86i6vakmjc71gkvb8mmb59pj9k4bcq-conformist-flake-outputs/bin/conformist-flake-outputs"
excludes = []
includes = ["flake.nix"]
options = []
passes-files = false

[linter.justfile-aggregate-comments]
command = "/nix/store/2dm0xkxkhmz5j00smbjn10a3h756811w-conformist-justfile-aggregate-comments/bin/conformist-justfile-aggregate-comments"
excludes = []
includes = ["justfile"]
options = []
passes-files = false

[linter.justfile-debug-recipes]
command = "/nix/store/9slrw12kkah5ly76vmgixv2mlw6aazz8-conformist-justfile-debug-recipes/bin/conformist-justfile-debug-recipes"
excludes = []
includes = ["justfile"]
options = []
passes-files = false

[linter.justfile-default]
command = "/nix/store/lnaxij7b9bq7dair5w9hmn3zr7nr9n7d-conformist-justfile-default/bin/conformist-justfile-default"
excludes = []
includes = ["justfile"]
options = []
passes-files = false

[linter.justfile-leaf-noun]
command = "/nix/store/5xan76lpzk8bxishxfxprbhqby69qxjx-conformist-justfile-leaf-noun/bin/conformist-justfile-leaf-noun"
excludes = []
includes = ["justfile"]
options = []
passes-files = false

[linter.justfile-recipe-descriptions]
command = "/nix/store/g3yblk6w1hl9njnib52hrzrgrj0m6m59-conformist-justfile-recipe-descriptions/bin/conformist-justfile-recipe-descriptions"
excludes = []
includes = ["justfile"]
options = []
passes-files = false

[linter.justfile-recipe-names]
command = "/nix/store/2k5y2whbivbghh1h3p9wcl0366fsqpl5-conformist-justfile-recipe-names/bin/conformist-justfile-recipe-names"
excludes = []
includes = ["justfile"]
options = []
passes-files = false

[linter.justfile-task-hierarchy]
command = "/nix/store/xh88fkkgj9j8yf7v7r8an29zlknkalk3-conformist-justfile-task-hierarchy/bin/conformist-justfile-task-hierarchy"
excludes = []
includes = ["justfile"]
options = []
passes-files = false
